# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs
puppet_bin=/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:/opt/puppet/bin
gem_bin=~/bin
PATH=$gem_bin:$puppet_bin:$PATH:$HOME/bin
export GEM_HOME="${HOME}/.gems"
export PATH
